### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by ic-kashey** [EvgenijM86/emercoin#4]
* CentOS7
* emercoind v0.3.4emc-1-g48d728d-dirty-beta (compiled from source)

`emercoind getinfo` stuck, PRC thread (thread 7, right?) waiting for lock forever.

Issue is fully reproducible, but seems like only when I have a some money in wallet.

Fresh installation, blockchain reloading and importprivkey does not help.
I.e. emercoind works fine until importprivkey is performed.
After importprivkey `emercoind getinfo` successful one/two times, sometimes after 3-5 MINUTES pause. Further `emercoind getinfo` stuck forever.

You are welcome to ask for additional tests/debug/etc.

```
(gdb) thread 1
[Switching to thread 1 (Thread 0x7f5805fb6840 (LWP 18425))]
#0  0x00007f580406f653 in recvfrom () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f580406f653 in recvfrom () from /lib64/libpthread.so.0
#1  0x000000000060618f in recvfrom (__addr_len=0x4d768f8, __addr=0x4d768d8, __flags=0, __n=1024, __buf=<optimized out>, __fd=<optimized out>) at /usr/include/bits/socket2.h:76
#2  EmcDns::Run (this=0x4d76660) at emcdns.cpp:289
#3  0x00000000004dbb2b in AppInit2 (argc=1, argv=0x7fffb44bb188) at init.cpp:658
#4  0x00000000004dc94a in AppInit (argc=<optimized out>, argv=<optimized out>) at init.cpp:132
#5  0x00000000004a4349 in main (argc=<optimized out>, argv=<optimized out>) at init.cpp:118
(gdb) thread 2
[Switching to thread 2 (Thread 0x7f57db7fe700 (LWP 18436))]
#0  0x00007f580350a053 in __memcmp_sse2 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f580350a053 in __memcmp_sse2 () from /lib64/libc.so.6
#1  0x00000000005c26f7 in Lookup (key=..., this=0x7f57db7fcd60) at uint256hm.h:132
#2  uint256HashMap<StakeMod>::Insert (this=this@entry=0x7f57db7fcd60, key=..., value=...) at uint256hm.h:107
#3  0x00000000005c27d2 in uint256HashMap<StakeMod>::Insert (this=this@entry=0x8c83c0 <StakeModCache>, key=..., value=...) at uint256hm.h:98
#4  0x00000000005bfc2d in GetKernelStakeModifier (fPrintProofOfStake=false, nStakeModifierTime=<synthetic pointer>, nStakeModifierHeight=<synthetic pointer>, nStakeModifier=<synthetic pointer>,
    hashBlockFrom=...) at kernel.cpp:279
#5  CheckStakeKernelHash (nBits=nBits@entry=470313667, blockFrom=..., nTxPrevOffset=nTxPrevOffset@entry=160, txPrev=..., prevout=..., nTimeTx=nTimeTx@entry=1447760741, hashProofOfStake=...,
    fPrintProofOfStake=fPrintProofOfStake@entry=false) at kernel.cpp:331
#6  0x00000000005b0565 in CWallet::CreateCoinStake (this=this@entry=0x47d9b40, keystore=..., nBits=470313667, nSearchInterval=6, txNew=...) at wallet.cpp:1384
#7  0x00000000004f8ae8 in CreateNewBlock (pwallet=pwallet@entry=0x47d9b40, fProofOfStake=fProofOfStake@entry=true) at main.cpp:3751
#8  0x0000000000501cbb in BitcoinMiner (pwallet=pwallet@entry=0x47d9b40, fProofOfStake=fProofOfStake@entry=true) at main.cpp:4081
#9  0x000000000051dd66 in ThreadStakeMinter (parg=0x47d9b40) at net.cpp:1440
#10 0x00007f5804068df5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f58035771ad in clone () from /lib64/libc.so.6
(gdb) thread 3
[Switching to thread 3 (Thread 0x7f57d37fe700 (LWP 18435))]
#0  0x00007f580353e48d in nanosleep () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f580353e48d in nanosleep () from /lib64/libc.so.6
#1  0x00007f580356f014 in usleep () from /lib64/libc.so.6
#2  0x000000000051eab6 in Sleep (n=100000) at util.h:104
#3  ThreadDumpAddress2 (parg=parg@entry=0x0) at net.cpp:1079
#4  0x000000000051eb60 in ThreadDumpAddress (parg=0x0) at net.cpp:1090
#5  0x00007f5804068df5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f58035771ad in clone () from /lib64/libc.so.6
(gdb) thread 4
[Switching to thread 4 (Thread 0x7f57dbfff700 (LWP 18434))]
#0  0x00007f580406ef7d in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f580406ef7d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f580406ad4d in _L_lock_840 () from /lib64/libpthread.so.0
#2  0x00007f580406ac6a in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00000000004aedb5 in lock (this=<optimized out>) at /usr/include/boost/thread/pthread/recursive_mutex.hpp:107
#4  lock (this=<optimized out>) at sync.h:64
#5  lock (this=0x7f57dbffec60) at /usr/include/boost/thread/lock_types.hpp:344
#6  Enter (pszName=<optimized out>, pszFile=<optimized out>, nLine=<optimized out>, this=0x7f57dbffec60) at sync.h:112
#7  CMutexLock<AnnotatedMixin<boost::recursive_mutex> >::CMutexLock (this=0x7f57dbffec60, mutexIn=..., pszName=<optimized out>, pszFile=<optimized out>, nLine=<optimized out>, fTry=<optimized out>)
    at sync.h:133
#8  0x0000000000500ddf in ProcessMessages (pfrom=pfrom@entry=0x7f57cc003390) at main.cpp:3407
#9  0x000000000051f6b5 in ThreadMessageHandler2 (parg=parg@entry=0x0) at net.cpp:1398
#10 0x000000000051f957 in ThreadMessageHandler (parg=0x0) at net.cpp:1361
#11 0x00007f5804068df5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007f58035771ad in clone () from /lib64/libc.so.6
(gdb) thread 5
[Switching to thread 5 (Thread 0x7f57f0ff9700 (LWP 18433))]
#0  0x00007f580353e48d in nanosleep () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f580353e48d in nanosleep () from /lib64/libc.so.6
#1  0x00007f580356f014 in usleep () from /lib64/libc.so.6
#2  0x000000000052374b in Sleep (n=255) at util.h:104
#3  ThreadOpenConnections2 (parg=parg@entry=0x0) at net.cpp:1157
#4  0x0000000000523f57 in ThreadOpenConnections (parg=0x0) at net.cpp:1104
#5  0x00007f5804068df5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f58035771ad in clone () from /lib64/libc.so.6
(gdb) thread 6
[Switching to thread 6 (Thread 0x7f57f1ffb700 (LWP 18431))]
#0  0x00007f580353e48d in nanosleep () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f580353e48d in nanosleep () from /lib64/libc.so.6
#1  0x00007f580356f014 in usleep () from /lib64/libc.so.6
#2  0x0000000000521c8a in Sleep (n=10) at util.h:104
#3  ThreadSocketHandler2 (parg=parg@entry=0x0) at net.cpp:820
#4  0x00000000005228e7 in ThreadSocketHandler (parg=0x0) at net.cpp:488
#5  0x00007f5804068df5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f58035771ad in clone () from /lib64/libc.so.6
(gdb) thread 7
[Switching to thread 7 (Thread 0x7f57f37fe700 (LWP 18428))]
#0  0x00007f580406ef7d in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f580406ef7d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f580406ad4d in _L_lock_840 () from /lib64/libpthread.so.0
#2  0x00007f580406ac6a in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00000000004aedb5 in lock (this=<optimized out>) at /usr/include/boost/thread/pthread/recursive_mutex.hpp:107
#4  lock (this=<optimized out>) at sync.h:64
#5  lock (this=0x7f57f37fd880) at /usr/include/boost/thread/lock_types.hpp:344
#6  Enter (pszName=<optimized out>, pszFile=<optimized out>, nLine=<optimized out>, this=0x7f57f37fd880) at sync.h:112
#7  CMutexLock<AnnotatedMixin<boost::recursive_mutex> >::CMutexLock (this=0x7f57f37fd880, mutexIn=..., pszName=<optimized out>, pszFile=<optimized out>, nLine=<optimized out>, fTry=<optimized out>)
    at sync.h:133
#8  0x000000000054d8fc in ThreadRPCServer2 (parg=parg@entry=0x0) at bitcoinrpc.cpp:3237
#9  0x000000000054f677 in ThreadRPCServer (parg=0x0) at bitcoinrpc.cpp:3054
#10 0x00007f5804068df5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f58035771ad in clone () from /lib64/libc.so.6
(gdb) thread 8
[Switching to thread 8 (Thread 0x7f57f8e8a700 (LWP 18426))]
#0  0x00007f580353e48d in nanosleep () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f580353e48d in nanosleep () from /lib64/libc.so.6
#1  0x00007f580356f014 in usleep () from /lib64/libc.so.6
#2  0x00000000005bdb27 in Sleep (n=500) at util.h:104
#3  ThreadFlushWalletDB (parg=0x47d9c60) at walletdb.cpp:344
#4  0x00007f5804068df5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f58035771ad in clone () from /lib64/libc.so.6
(gdb) thread 9
Thread ID 9 not known.
```

**Comment by EvgenijM86** [comment]
Thank you for your report. I will look into in a couple of days.
